// components/student-dashboard.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Upload, FileText, Search, Clock, CheckCircle, XCircle } from "lucide-react"

export function StudentDashboard() {
  const recentWorks = [
    {
      id: 1,
      title: "Sistema de Gestión Universitaria",
      subject: "Programación Web",
      status: "approved",
      date: "2024-01-15",
    },
    {
      id: 2,
      title: "Análisis de Algoritmos de Ordenamiento",
      subject: "Estructuras de Datos",
      status: "pending",
      date: "2024-01-10",
    },
    { id: 3, title: "Base de Datos para E-commerce", subject: "Base de Datos", status: "rejected", date: "2024-01-05" },
  ]

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "approved":
        return (
          <Badge className="bg-green-100 text-green-800">
            <CheckCircle className="w-3 h-3 mr-1" />
            Aprobado
          </Badge>
        )
      case "pending":
        return (
          <Badge className="bg-yellow-100 text-yellow-800">
            <Clock className="w-3 h-3 mr-1" />
            Pendiente
          </Badge>
        )
      case "rejected":
        return (
          <Badge className="bg-red-100 text-red-800">
            <XCircle className="w-3 h-3 mr-1" />
            Rechazado
          </Badge>
        )
      default:
        return <Badge>Desconocido</Badge>
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold text-gray-900">Dashboard del Estudiante</h2>
        <p className="text-gray-600">Bienvenido al sistema de gestión de trabajos académicos</p>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Trabajos Subidos</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">12</div>
            <p className="text-xs text-muted-foreground">+2 este mes</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Aprobados</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">8</div>
            <p className="text-xs text-muted-foreground">66.7% de aprobación</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Pendientes</CardTitle>
            <Clock className="h-4 w-4 text-yellow-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-600">3</div>
            <p className="text-xs text-muted-foreground">En revisión</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Rechazados</CardTitle>
            <XCircle className="h-4 w-4 text-red-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-red-600">1</div>
            <p className="text-xs text-muted-foreground">Requiere revisión</p>
          </CardContent>
        </Card>
      </div>

      {/* Quick Actions */}
      <Card>
        <CardHeader>
          <CardTitle>Acciones Rápidas</CardTitle>
          <CardDescription>Gestiona tus trabajos académicos</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Button className="bg-green-600 hover:bg-green-700 h-20 flex flex-col">
              <Upload className="h-6 w-6 mb-2" />
              Subir Nuevo Trabajo
            </Button>
            <Button variant="outline" className="h-20 flex flex-col">
              <FileText className="h-6 w-6 mb-2" />
              Ver Mis Trabajos
            </Button>
            <Button variant="outline" className="h-20 flex flex-col">
              <Search className="h-6 w-6 mb-2" />
              Buscar Trabajos
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Recent Works */}
      <Card>
        <CardHeader>
          <CardTitle>Trabajos Recientes</CardTitle>
          <CardDescription>Tus últimos trabajos subidos</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {recentWorks.map((work) => (
              <div key={work.id} className="flex items-center justify-between p-4 border rounded-lg">
                <div>
                  <h4 className="font-semibold">{work.title}</h4>
                  <p className="text-sm text-gray-600">{work.subject}</p>
                  <p className="text-xs text-gray-500">{work.date}</p>
                </div>
                <div className="flex items-center space-x-2">
                  {getStatusBadge(work.status)}
                  <Button variant="ghost" size="sm">
                    Ver
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// src/app/components/student/student-dashboard.component.ts
import { Component, type OnInit } from "@angular/core"
import { CommonModule } from "@angular/common"
import { StatsCardComponent } from "../shared/stats-card/stats-card.component"
import { BreadcrumbComponent, type BreadcrumbItem } from "../shared/breadcrumb/breadcrumb.component"
import { UserService } from "../../services/user.service"
import type { Work } from "../../models/work.model"
import  { WorkService } from "../../services/work.service"

@Component({
  selector: "app-student-dashboard",
  standalone: true,
  imports: [CommonModule, StatsCardComponent, BreadcrumbComponent],
  template: `
    <div class="container-fluid">
      <!-- Breadcrumb -->
      <app-breadcrumb [items]="breadcrumbItems" class="mb-3"></app-breadcrumb>
      
      <div class="row mb-4">
        <div class="col">
          <h2 class="display-6 fw-bold text-dark">Dashboard del Estudiante</h2>
          <p class="text-muted">Bienvenido al sistema de gestión de trabajos académicos</p>
        </div>
      </div>

      <!-- Stats Cards -->
      <div class="row mb-4">
        <div class="col-md-3 mb-3">
          <app-stats-card
            title="Trabajos Subidos"
            [value]="12"
            subtitle="+2 este mes"
            icon="bi-file-text"
            subtitleClass="text-success">
          </app-stats-card>
        </div>

        <div class="col-md-3 mb-3">
          <app-stats-card
            title="Aprobados"
            [value]="8"
            subtitle="66.7% de aprobación"
            icon="bi-check-circle"
            valueClass="text-success"
            iconClass="text-success">
          </app-stats-card>
        </div>

        <div class="col-md-3 mb-3">
          <app-stats-card
            title="Pendientes"
            [value]="3"
            subtitle="En revisión"
            icon="bi-clock"
            valueClass="text-warning"
            iconClass="text-warning">
          </app-stats-card>
        </div>

        <div class="col-md-3 mb-3">
          <app-stats-card
            title="Rechazados"
            [value]="1"
            subtitle="Requiere revisión"
            icon="bi-x-circle"
            valueClass="text-danger"
            iconClass="text-danger">
          </app-stats-card>
        </div>
      </div>

      <!-- Quick Actions -->
      <div class="row mb-4">
        <div class="col">
          <div class="card">
            <div class="card-header bg-white">
              <h5 class="card-title mb-0">Acciones Rápidas</h5>
              <small class="text-muted">Gestiona tus trabajos académicos</small>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-4 mb-3">
                  <button class="btn btn-success w-100 py-4 action-btn">
                    <i class="bi bi-cloud-upload fs-2 d-block mb-2"></i>
                    <span class="fw-semibold">Subir Nuevo Trabajo</span>
                  </button>
                </div>
                <div class="col-md-4 mb-3">
                  <button class="btn btn-outline-secondary w-100 py-4 action-btn">
                    <i class="bi bi-file-text fs-2 d-block mb-2"></i>
                    <span class="fw-semibold">Ver Mis Trabajos</span>
                  </button>
                </div>
                <div class="col-md-4 mb-3">
                  <button class="btn btn-outline-secondary w-100 py-4 action-btn">
                    <i class="bi bi-search fs-2 d-block mb-2"></i>
                    <span class="fw-semibold">Buscar Trabajos</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Recent Works -->
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header bg-white">
              <h5 class="card-title mb-0">Trabajos Recientes</h5>
              <small class="text-muted">Tus últimos trabajos subidos</small>
            </div>
            <div class="card-body">
              <div *ngFor="let work of recentWorks" class="border rounded p-3 mb-3 work-item">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="flex-grow-1">
                    <h6 class="fw-bold mb-1">{{ work.title }}</h6>
                    <p class="text-muted small mb-1">
                      <i class="bi bi-book me-1"></i>{{ work.subject }}
                    </p>
                    <small class="text-muted">
                      <i class="bi bi-calendar3 me-1"></i>{{ work.date }}
                    </small>
                  </div>
                  <div class="d-flex align-items-center">
                    <span [class]="getStatusBadgeClass(work.status)" class="badge me-2">
                      <i [class]="getStatusIcon(work.status)" class="me-1"></i>
                      {{ getStatusText(work.status) }}
                    </span>
                    <button class="btn btn-sm btn-outline-primary">
                      <i class="bi bi-eye me-1"></i>Ver
                    </button>
                  </div>
                </div>
              </div>
              
              <div *ngIf="recentWorks.length === 0" class="text-center py-4">
                <i class="bi bi-file-text fs-1 text-muted d-block mb-3"></i>
                <p class="text-muted">No tienes trabajos recientes</p>
                <button class="btn btn-success">
                  <i class="bi bi-plus-circle me-2"></i>Subir tu primer trabajo
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
    .action-btn {
      transition: all 0.3s ease;
      border-radius: 0.5rem;
    }
    
    .action-btn:hover {
      transform: translateY(-2px);
      box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
    }
    
    .work-item {
      transition: all 0.2s ease;
      background-color: #f8f9fa;
    }
    
    .work-item:hover {
      background-color: #e9ecef;
      transform: translateX(5px);
    }
    
    .card-header {
      border-bottom: 1px solid #dee2e6;
    }
  `,
  ],
})
export class StudentDashboardComponent implements OnInit {
  recentWorks: Work[] = []
  breadcrumbItems: BreadcrumbItem[] = [
    { label: "Inicio", url: "/" },
    { label: "Dashboard", active: true },
  ]

  constructor(private workService: WorkService) {}

  ngOnInit(): void {
    this.workService.getWorks().subscribe((works) => {
      this.recentWorks = works.slice(0, 3)
    })
  }

  getStatusBadgeClass(status: string): string {
    switch (status) {
      case "approved":
        return "bg-success"
      case "pending":
        return "bg-warning text-dark"
      case "rejected":
        return "bg-danger"
      default:
        return "bg-secondary"
    }
  }

  getStatusIcon(status: string): string {
    switch (status) {
      case "approved":
        return "bi bi-check-circle"
      case "pending":
        return "bi bi-clock"
      case "rejected":
        return "bi bi-x-circle"
      default:
        return "bi bi-question-circle"
    }
  }

  getStatusText(status: string): string {
    switch (status) {
      case "approved":
        return "Aprobado"
      case "pending":
        return "Pendiente"
      case "rejected":
        return "Rechazado"
      default:
        return "Desconocido"
    }
  }
}
