// src/app/components/shared/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core"
import { CommonModule } from "@angular/common"
import { FormsModule } from "@angular/forms"

interface MenuItem {
  id: string
  label: string
  icon: string
}

@Component({
  selector: "app-sidebar",
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="bg-success text-white sidebar" style="width: 280px;">
      <div class="p-4">
        <div class="d-flex align-items-center mb-4">
          <i class="bi bi-mortarboard-fill me-2 fs-5"></i>
          <span class="fw-bold">Sistema Académico</span>
        </div>

        <select 
          class="form-select bg-success border-success text-white"
          [(ngModel)]="userRole"
          (ngModelChange)="onRoleChange($event)"
          style="background-image: none;">
          <option value="student">Estudiante</option>
          <option value="works-admin">Admin. Trabajos</option>
          <option value="users-admin">Admin. Usuarios</option>
        </select>
      </div>

      <nav class="px-3 pb-4">
        <button 
          *ngFor="let item of getMenuItems()"
          class="btn w-100 text-start mb-2 d-flex align-items-center"
          [class.btn-light]="activeView === item.id"
          [class.btn-outline-light]="activeView !== item.id"
          [class.text-success]="activeView === item.id"
          [class.text-white]="activeView !== item.id"
          (click)="onMenuClick(item.id)">
          <i [class]="'bi ' + item.icon + ' me-3'"></i>
          {{ item.label }}
        </button>
      </nav>
    </div>
  `,
  styles: [
    `
    .sidebar {
      min-height: 100vh;
      background: linear-gradient(180deg, #198754 0%, #146c43 100%);
    }
    
    .form-select option {
      background-color: #198754;
      color: white;
    }
    
    .btn-outline-light:hover {
      background-color: rgba(255, 255, 255, 0.1);
      border-color: rgba(255, 255, 255, 0.2);
    }
  `,
  ],
})
export class SidebarComponent {
  @Input() activeView!: string
  @Input() userRole!: "student" | "works-admin" | "users-admin"
  @Output() viewChanged = new EventEmitter<string>()
  @Output() roleChanged = new EventEmitter<"student" | "works-admin" | "users-admin">()

  private studentMenuItems: MenuItem[] = [
    { id: "student-dashboard", label: "Dashboard", icon: "bi-house-door" },
    { id: "upload-work", label: "Subir Trabajo", icon: "bi-cloud-upload" },
    { id: "my-works", label: "Mis Trabajos", icon: "bi-file-text" },
    { id: "search-works", label: "Buscar Trabajos", icon: "bi-search" },
    { id: "profile", label: "Mi Perfil", icon: "bi-person-gear" },
  ]

  private worksAdminMenuItems: MenuItem[] = [
    { id: "works-admin-dashboard", label: "Dashboard", icon: "bi-house-door" },
    { id: "manage-works", label: "Gestionar Trabajos", icon: "bi-file-text" },
    { id: "pending-works", label: "Trabajos Pendientes", icon: "bi-clock" },
    { id: "advanced-search", label: "Búsqueda Avanzada", icon: "bi-search" },
    { id: "statistics", label: "Estadísticas", icon: "bi-bar-chart" },
  ]

  private usersAdminMenuItems: MenuItem[] = [
    { id: "users-admin-dashboard", label: "Dashboard", icon: "bi-people" },
    { id: "manage-users", label: "Gestionar Usuarios", icon: "bi-person-gear" },
    { id: "create-user", label: "Crear Usuario", icon: "bi-person-plus" },
    { id: "system-stats", label: "Estadísticas Sistema", icon: "bi-bar-chart" },
    { id: "settings", label: "Configuración", icon: "bi-gear" },
  ]

  getMenuItems(): MenuItem[] {
    switch (this.userRole) {
      case "student":
        return this.studentMenuItems
      case "works-admin":
        return this.worksAdminMenuItems
      case "users-admin":
        return this.usersAdminMenuItems
      default:
        return this.studentMenuItems
    }
  }

  onMenuClick(viewId: string): void {
    this.viewChanged.emit(viewId)
  }

  onRoleChange(role: "student" | "works-admin" | "users-admin"): void {
    this.roleChanged.emit(role)
  }
}

// components/sidebar.tsx
"use client"

import {
  BookOpen,
  Upload,
  Search,
  FileText,
  Users,
  BarChart3,
  Settings,
  GraduationCap,
  Shield,
  UserCog,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

interface SidebarProps {
  activeView: string
  setActiveView: (view: string) => void
  userRole: "student" | "works-admin" | "users-admin"
  setUserRole: (role: "student" | "works-admin" | "users-admin") => void
}

export function Sidebar({ activeView, setActiveView, userRole, setUserRole }: SidebarProps) {
  const studentMenuItems = [
    { id: "student-dashboard", label: "Dashboard", icon: BookOpen },
    { id: "upload-work", label: "Subir Trabajo", icon: Upload },
    { id: "my-works", label: "Mis Trabajos", icon: FileText },
    { id: "search-works", label: "Buscar Trabajos", icon: Search },
    { id: "profile", label: "Mi Perfil", icon: Settings },
  ]

  const worksAdminMenuItems = [
    { id: "works-admin-dashboard", label: "Dashboard", icon: BookOpen },
    { id: "manage-works", label: "Gestionar Trabajos", icon: FileText },
    { id: "pending-works", label: "Trabajos Pendientes", icon: Upload },
    { id: "advanced-search", label: "Búsqueda Avanzada", icon: Search },
    { id: "statistics", label: "Estadísticas", icon: BarChart3 },
  ]

  const usersAdminMenuItems = [
    { id: "users-admin-dashboard", label: "Dashboard", icon: Users },
    { id: "manage-users", label: "Gestionar Usuarios", icon: UserCog },
    { id: "create-user", label: "Crear Usuario", icon: Users },
    { id: "system-stats", label: "Estadísticas Sistema", icon: BarChart3 },
    { id: "settings", label: "Configuración", icon: Settings },
  ]

  const getMenuItems = () => {
    switch (userRole) {
      case "student":
        return studentMenuItems
      case "works-admin":
        return worksAdminMenuItems
      case "users-admin":
        return usersAdminMenuItems
      default:
        return studentMenuItems
    }
  }

  const getRoleIcon = () => {
    switch (userRole) {
      case "student":
        return <GraduationCap className="h-5 w-5" />
      case "works-admin":
        return <Shield className="h-5 w-5" />
      case "users-admin":
        return <UserCog className="h-5 w-5" />
    }
  }

  return (
    <div className="bg-green-800 text-white w-64 flex flex-col">
      <div className="p-6">
        <div className="flex items-center space-x-2 mb-6">
          {getRoleIcon()}
          <span className="font-semibold">Sistema Académico</span>
        </div>

        <Select
          value={userRole}
          onValueChange={(value: "student" | "works-admin" | "users-admin") => setUserRole(value)}
        >
          <SelectTrigger className="bg-green-700 border-green-600 text-white">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="student">Estudiante</SelectItem>
            <SelectItem value="works-admin">Admin. Trabajos</SelectItem>
            <SelectItem value="users-admin">Admin. Usuarios</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <nav className="flex-1 px-4">
        {getMenuItems().map((item) => {
          const Icon = item.icon
          return (
            <Button
              key={item.id}
              variant={activeView === item.id ? "secondary" : "ghost"}
              className={`w-full justify-start mb-2 ${
                activeView === item.id
                  ? "bg-green-700 text-white"
                  : "text-green-100 hover:bg-green-700 hover:text-white"
              }`}
              onClick={() => setActiveView(item.id)}
            >
              <Icon className="mr-3 h-4 w-4" />
              {item.label}
            </Button>
          )
        })}
      </nav>
    </div>
  )
}
